name: static-check

on: [push, pull_request]

jobs:
  staticcheck:
    name: staticcheck (project)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2023.1.3"
env:
  GO_VERSION: 1.20.x
